name: debt-manager

services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: debt_manager
      POSTGRES_PASSWORD: password
      POSTGRES_DB: debt_manager_development
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U debt_manager"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      target: development
    environment:
      DATABASE_URL: postgres://debt_manager:password@db:5432/debt_manager_development
      RAILS_ENV: development
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true

volumes:
  postgres_dev_data:
